secrets:
- kmsKeyName: projects/testing-192515/locations/global/keyRings/github-keyring/cryptoKeys/github-token
  secretEnv:
    GITHUB: "CiQATCXijDFx3wTME12zXaUjStIZOyNdRR9ofmyn0iMRc+ifpwYSUQDGtndZa2snc6lLZiXaYmET
             ujTdvcRI6SoBcVjuxKL74T5qo4yjN2OK/+LgGTVB7r2fWt6IOxCXPVvpdndgWP9SCvIUIq2QORdZ
             Y7pYJ4C2Mw=="

steps:
# Playing with GO
- name: 'gcr.io/cloud-builders/go'
  entrypoint: 'ash' # because this is alpine
  args:
  - -c
  - |
    ash privateRepoAccess # Exec script to configure Repos' Private Access
    cd functions
    for d in */ ; do # Now we vendor all the functions
      cd $d
      pwd
      go mod tidy
      go mod vendor
      rm -f go.mod
      rm -f go.sum
      cd ..
    done
  secretEnv: ['GITHUB']
  env:
    - TEST="${_PREFIX}"

# Build and Deploy Cloud Functions
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - alpha
  - functions
  - deploy
  - ${_PREFIX}-func1
  - --trigger-http
  - --entry-point=BrezBaze
  - --runtime=go111
  - --memory=128MB
  dir: 'functions/noDBExp'